[versions]
kotlin = "1.8.10"

[libraries]
org-ajoberstar-grgit-gradle-plugin = "org.ajoberstar.grgit:org.ajoberstar.grgit.gradle.plugin:5.0.0"

[plugins]
com-github-ben-manes-versions = "com.github.ben-manes.versions:0.45.0"
