name: Cleanup npm Snapshots
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  cleanup:
    name: "Deprecate npm snapshot versions"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 24
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Cleanup npm snapshots
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./gradlew cleanupNpmSnapshots
